In [2]:
import numpy as np

In [1]:
a = [1, 2, 3, 4, 5]
b = [5, 4, 3, 2, 1]

a[0] is b[-1]

True

In [3]:
a = np.array(a)
b = np.array(b)

a[0] is b[-1]

False

In [4]:
test_array = np.array([1, 4, 5, "8"], float)
test_array

array([1., 4., 5., 8.])

In [5]:
matrix = [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
np.array(matrix, int).shape

(3, 4)

In [7]:
tensor = [[[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
          [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
          [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
          [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]]
np.array(tensor, int).shape

(4, 3, 4)

# Comparison

In [8]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
a < 4 # Broadcasting이 일어나서 모든 요소에서 4보다 작은지 확인

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [11]:
a < 1

array([ True, False, False, False, False, False, False, False, False,
       False])

In [12]:
a < 10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [13]:
np.any(a>5), np.any(a<0) # numpy.any() : 하나라도 true면 true, false면 false

(True, False)

In [15]:
np.all(a<5), np.all(a<10)# numpy.all() : 모두가 true면 true

(False, True)

In [16]:
test_a = np.array([1, 3, 0], float)
test_b = np.array([5, 2, 1], float)
test_a > test_b

array([False,  True, False])

In [17]:
a = np.array([1, 3, 0], float)
np.logical_and(a > 0, a < 3) # and 비교연산이라고 생각

array([ True, False, False])

In [18]:
b = np.array([True, False, True], bool)
np.logical_not(b) # not 연산

array([False,  True, False])

In [19]:
np.where(a > 0, 3, 2) # numpy.where(condition, TRUE return, FALSE return)

array([3, 3, 2])

In [20]:
a = np.arange(10)
np.where(a > 5) # numpy.where(condition) : True index return

(array([6, 7, 8, 9], dtype=int64),)

In [21]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a) # NaN condition check

array([False,  True, False])

In [22]:
np.isinf(a) # Inf condition check

array([False, False,  True])

In [23]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 19, 10])
np.argmax(a) # numpy.argmax() : 가장 큰 값의 Index

8

In [25]:
np.argmin(a) # numpy.argmin() : 가장 작은 값의 Index

0

In [26]:
a.argsort() # numpy.argsort() : 오름차순의 value에 대해 Index return

array([0, 1, 2, 3, 4, 5, 6, 7, 9, 8], dtype=int64)

# Boolean & Fancy Index

In [28]:
test_array = np.array([1, 4, 0, 2, 3, 8, 9, 7], float)
test_array>3

array([False,  True, False, False, False,  True,  True,  True])

In [29]:
test_array.shape

(8,)

In [30]:
(test_array > 3).shape

(8,)

In [31]:
test_array[test_array > 3] # boolean_index를 이용해서, value를 확인 가능

array([4., 8., 9., 7.])

In [32]:
condition = test_array < 3
test_array[condition]

array([1., 0., 2.])

In [33]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int) # integer를 넣어서, 한번에 여러 값index로 사용 가능
a[b]

array([2., 2., 4., 8., 6., 4.])

In [34]:
a.take(b) # 똑같음

array([2., 2., 4., 8., 6., 4.])

In [35]:
a = np.array([[ 1, 4],
              [9, 16]], float) # matrix에서도
b = np.array([0, 0, 1, 1, 0], int) # row Index로
c = np.array([0, 1, 1, 1, 1], int) # column Index로 사용 가능
a[b, c]

array([ 1.,  4., 16., 16.,  4.])

# numpy File I/O

In [37]:
a = np.loadtxt('./populations.txt', delimiter="\t")
a

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.]])

In [39]:
a_int = a.astype(int)
a_int_3 = a_int[:3]

In [40]:
np.savetxt("int_data_2.csv", a_int_3, fmt="%.2e", delimiter=",")

In [42]:
np.save("npy_test_object", arr=a_int_3)

In [43]:
a_test = np.load(file="npy_test_object.npy")
a_test

array([[ 1900, 30000,  4000, 48300],
       [ 1901, 47200,  6100, 48200],
       [ 1902, 70200,  9800, 41500]])

In [44]:
npy_array = np.load(file="npy_test_object.npy")
npy_array

array([[ 1900, 30000,  4000, 48300],
       [ 1901, 47200,  6100, 48200],
       [ 1902, 70200,  9800, 41500]])