In [1]:
import numpy as np

In [2]:
x = np.array([1, 7, 2])
y = np.array([5, 2, 1])
x + y

array([6, 9, 3])

In [3]:
x - y

array([-4,  5,  1])

In [4]:
x * y

array([ 5, 14,  2])

In [5]:
def l1_norm(x):
	x_norm = np.abs(x)
	x_norm = np.sum(x_norm)
	return x_norm

def l2_norm(x):
	x_norm = x*x
	x_norm = np.sum(x_norm)
	x_norm = np.sqrt(x_norm)
	return x_norm

In [6]:
x = np.array([3, 4])

In [7]:
l1_norm(x)

7

In [8]:
l2_norm(x)

5.0

In [9]:
def angle(x, y):
	v = np.inner(x, y) / (l2_norm(x) * l2_norm(y)) # 내적을 이용한 cos(theta) 계산
	theta = np.arccos(v) # cos(theta)에 arccos을 씌우면 theta만 남는다

	return theta

In [13]:
angle(np.array([1, np.sqrt(3)]), np.array([1, 0]))

1.0471975511965976