In [1]:
import numpy as np

In [2]:
X = np.array([[1, -2, 3],
			  [7, 5, 0],
			  [-2, -1, 2]])
Y = np.array([[0, 1],
			  [1, -1],
			  [-2, 1]])

In [3]:
X @ Y #  행렬 곱  X i번째 행백터 와 Y j번째 열백터의 내적값들

array([[-8,  6],
       [ 5,  2],
       [-5,  1]])

In [5]:
X = np.array([[1, -2, 3],
			  [7, 5, 0],
			  [-2, -1, 2]])
Y = np.array([[0, 1, -1],
			  [1, -1, 0]])

In [6]:
np.inner(X, Y) # numpy.inner(X ,Y) : X의 i번째 행백터, Y의 j번째 행백터 사이의 내적 -> 수학에서의 내적과는 다르다!

array([[-5,  3],
       [ 5,  2],
       [-3, -1]])

In [13]:
X = np.array([[1, -2, 3],
			  [7, 5, 0],
			  [-2, -1, 2]])

In [14]:
np.linalg.inv(X) # numpy.linalg.inv() : 행렬식(determinant)가 0이 아닌경우 역행렬을 구해준다!

array([[ 0.21276596,  0.0212766 , -0.31914894],
       [-0.29787234,  0.17021277,  0.44680851],
       [ 0.06382979,  0.10638298,  0.40425532]])

In [15]:
X @ np.linalg.inv(X)

array([[ 1.00000000e+00, -1.38777878e-17,  0.00000000e+00],
       [-2.22044605e-16,  1.00000000e+00, -5.55111512e-17],
       [-2.77555756e-17,  0.00000000e+00,  1.00000000e+00]])

In [16]:
Y = np.array([[0, 1],
			  [1, -1],
			  [-2 ,1]])

In [17]:
np.linalg.pinv(Y) # numpy.linalg.pinv() : 역행렬에 조건(행의 갯수와 열의 갯수가 동일)에 맞지 앟는 행렬의 유사 역행렬을 구해준다.(pseudo Inverse)

array([[ 5.00000000e-01,  4.09730229e-17, -5.00000000e-01],
       [ 8.33333333e-01, -3.33333333e-01, -1.66666667e-01]])

In [18]:
np.linalg.pinv(Y) @ Y

array([[ 1.00000000e+00, -2.22044605e-16],
       [ 0.00000000e+00,  1.00000000e+00]])

## Matrix Multiplications as Column Combinations

In [19]:
c = np.array([1, 2, 3])
bases = np.array([[1, 1, 0],
				  [1, 0, 1],
				  [1, -1, 1]])

In [20]:
c @ bases

array([ 6, -2,  5])